# Generated by Django 3.0.9 on 2021-11-10 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kvartira', models.IntegerField(blank='Квартира', verbose_name='Квартира')),
                ('email', models.EmailField(blank='Email', max_length=254, verbose_name='Почта')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Счетчику',
                'verbose_name_plural': 'Счетчики',
            },
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kvartira', models.IntegerField(blank='Квартира', verbose_name='Квартира')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('hot1', models.IntegerField(blank='1 горячего счетчика', verbose_name='1 горячего счетчика')),
                ('cold1', models.IntegerField(blank='1 холодного счетчика', verbose_name='1 холодного счетчика')),
                ('hot2', models.IntegerField(blank='1 горячего счетчика', null=True, verbose_name='2 горячего счетчика')),
                ('cold2', models.IntegerField(blank='1 холодного счетчика', null=True, verbose_name='2 холодного счетчика')),
                ('hot3', models.IntegerField(blank='1 горячего счетчика', null=True, verbose_name='3 горячего счетчика')),
                ('cold3', models.IntegerField(blank='1 холодного счетчика', null=True, verbose_name='3 холодного счетчика')),
                ('hot4', models.IntegerField(blank='1 горячего счетчика', null=True, verbose_name='4 горячего счетчика')),
                ('cold4', models.IntegerField(blank='1 холодного счетчика', null=True, verbose_name='4 холодного счетчика')),
                ('hot5', models.IntegerField(blank='1 горячего счетчика', null=True, verbose_name='5 горячего счетчика')),
                ('cold5', models.IntegerField(blank='1 холодного счетчика', null=True, verbose_name='5 холодного счетчика')),
                ('hot6', models.IntegerField(blank='1 горячего счетчика', null=True, verbose_name='6 горячего счетчика')),
                ('cold6', models.IntegerField(blank='1 холодного счетчика', null=True, verbose_name='6 холодного счетчика')),
                ('date', models.DateField(blank='Дата показания счетчиков', verbose_name='Дата показания счетчиков')),
            ],
            options={
                'verbose_name': 'Счетчику',
                'verbose_name_plural': 'Счетчики',
            },
        ),
        migrations.CreateModel(
            name='WaterKeep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair_count', models.IntegerField(blank='Количество пар счетчиков', null=True, verbose_name='Количество пар счетчиков')),
                ('hot1', models.IntegerField(blank='Номер 1 горячего счетчика', null=True, verbose_name='Номер 1 горячего счетчика')),
                ('cold1', models.IntegerField(blank='Номер 1 холодного счетчика', null=True, verbose_name='Номер 1 холодного счетчика')),
                ('hot2', models.IntegerField(blank='Номер 1 горячего счетчика', null=True, verbose_name='Номер 2 горячего счетчика')),
                ('cold2', models.IntegerField(blank='Номер 1 холодного счетчика', null=True, verbose_name='Номер 2 холодного счетчика')),
                ('hot3', models.IntegerField(blank='Номер 1 горячего счетчика', null=True, verbose_name='Номер 3 горячего счетчика')),
                ('cold3', models.IntegerField(blank='Номер 1 холодного счетчика', null=True, verbose_name='Номер 3 холодного счетчика')),
                ('hot4', models.IntegerField(blank='Номер 1 горячего счетчика', null=True, verbose_name='Номер 4 горячего счетчика')),
                ('cold4', models.IntegerField(blank='Номер 1 холодного счетчика', null=True, verbose_name='Номер 4 холодного счетчика')),
                ('hot5', models.IntegerField(blank='Номер 1 горячего счетчика', null=True, verbose_name='Номер 5 горячего счетчика')),
                ('cold5', models.IntegerField(blank='Номер 1 холодного счетчика', null=True, verbose_name='Номер 5 холодного счетчика')),
                ('hot6', models.IntegerField(blank='Номер 1 горячего счетчика', null=True, verbose_name='Номер 6 горячего счетчика')),
                ('cold6', models.IntegerField(blank='Номер 1 холодного счетчика', null=True, verbose_name='Номер 6 холодного счетчика')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Жилец')),
            ],
        ),
    ]
