# Generated by Django 3.0.9 on 2021-11-10 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_letter_water_waterkeep'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter',
            options={'verbose_name': 'Письмо от жителя', 'verbose_name_plural': 'Письма от жителей'},
        ),
        migrations.AlterModelOptions(
            name='water',
            options={'verbose_name': 'Показания Счетчиков', 'verbose_name_plural': 'Показания Счетчиков'},
        ),
        migrations.AlterModelOptions(
            name='waterkeep',
            options={'verbose_name': 'Номера счетчиков', 'verbose_name_plural': 'Номера счетчиков'},
        ),
        migrations.AlterField(
            model_name='letter',
            name='text',
            field=models.TextField(verbose_name='Письмо'),
        ),
        migrations.AlterField(
            model_name='waterkeep',
            name='pair_count',
            field=models.IntegerField(blank='Количество пар счетчиков', default=1, verbose_name='Количество пар счетчиков'),
        ),
        migrations.AlterField(
            model_name='waterkeep',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Жилец'),
        ),
    ]
